### ISSUE TITLE
bluemarble demo broken

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#429]
The total electon content demo doesn't work in Iris 1.3:
http://pelson.github.com/iris/examples/graphics/TEC.html#TEC

```
AttributeError                            Traceback (most recent call last)
<ipython-input-30-79c12b8eba35> in <module>()
      4 plt.xlabel('longitude / degrees')
      5 plt.ylabel('latitude / degrees')
----> 6 iplt.gcm().bluemarble(zorder=-1)

AttributeError: 'module' object has no attribute 'gcm'
```

I gather this is from the switch from Basemap to Cartopy.   Is there a workaround?
